spring:
  application:
    name: cccrawler
  kafka:
    bootstrap-servers: 47.94.216.42:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO

kafka:
  default:
    topic: tradedata

exchange:
  list:
    - name: binance
      btcusdt: https://api.binance.com/api/v1/trades?symbol=BTCUSDT&limit=10
      ethusdt: https://api.binance.com/api/v1/trades?symbol=ETHUSDT&limit=10