spring:
  application:
    name: cccrawler
  kafka:
    bootstrap-servers: 47.94.216.42:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO

kafka:
  default:
    topic: tradedatanew

exchange:
  list:
    - name: binance
      tradeurl: https://api.binance.com/api/v1/trades?symbol=%s&limit=10
      #klineurl: https://api.binance.com/api/v1/klines?symbol=%s&interval=1m&limit=5
      #逗号分割不同的symbol，竖线前面是查询用的，后面是发送消息用的
      symbols: CMTBTC|CMTBTC,CMTETH|CMTETH,CMTBNB|CMTBNB
      period: 10
    - name: huobipro
      tradeurl: https://api.huobipro.com/market/history/trade?symbol=%s&size=10
      #klineurl: https://api.huobipro.com/market/history/kline?period=1min&size=5&symbol=%s
      symbols: cmtbtc|CMTBTC,cmteth|CMTETH
      period: 10
    - name: okex
      tradeurl: https://www.okex.com/api/v1/trades.do?symbol=%s
      #klineurl: https://www.okex.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: cmt_usdt|CMTUSDT,cmt_btc|CMTBTC,cmt_bch|CMTBCH,cmt_eth|CMTETH
      period: 10