spring:
  application:
    name: cccrawler
  kafka:
    bootstrap-servers: 47.94.216.42:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO

kafka:
  default:
    topic: tradedata

exchange:
  list:
    - name: binance
      tradeurl: https://api.binance.com/api/v1/trades?symbol=%s&limit=10
      klineurl: https://api.binance.com/api/v1/klines?symbol=%s&interval=1m&limit=5
      symbols: BTCUSDT|BTCUSDT,ETHUSDT|ETHUSDT #逗号分割不同的symbol，竖线前面是查询用的，后面是发送消息用的
    - name: zb
      tradeurl: http://api.zb.com/data/v1/trades?market=%s
      klineurl: http://api.zb.com/data/v1/kline?market=%s&type=1min&size=5
      symbols: btc_usdt|BTCUSDT,eth_usdt|ETHUSDT
    - name: huobipro
      tradeurl: https://api.huobipro.com/market/history/trade?symbol=%s&size=10
      klineurl: https://api.huobipro.com/market/history/kline?period=1min&size=5&symbol=%s
      symbols: btcusdt|BTCUSDT,ethusdt|ETHUSDT
    - name: okex
      tradeurl: https://www.okex.com/api/v1/trades.do?symbol=%s
      klineurl: https://www.okex.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: btc_usdt|BTCUSDT,eth_usdt|ETHUSDT
    - name: okcoinusd
      tradeurl: https://www.okcoin.com/api/v1/trades.do?symbol=%s
      klineurl: https://www.okcoin.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: btc_usd|BTCUSDT,eth_usd|ETHUSDT
    - name: bittrex
      tradeurl: https://bittrex.com/api/v1.1/public/getmarkethistory?market=%s
      #klineurl: https://www.okcoin.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: USDT-BTC|BTCUSDT,USDT-ETH|ETHUSDT
    - name: bitstamp
      tradeurl: https://www.bitstamp.net/api/v2/transactions/%s/?time=minute
      #klineurl: https://www.okcoin.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: btcusd|BTCUSDT,ethusd|ETHUSDT
    #- name: kraken
    #  tradeurl: https://api.kraken.com/0/public/Trades?pair=%s
      #klineurl: https://www.okcoin.com/api/v1/kline.do?symbol=%s&type=1min&size=5
    #  symbols: XETHZUSD|ETHUSDT
    - name: gateio
      tradeurl: http://data.gateio.io/api2/1/tradeHistory/%s
      #klineurl: https://www.okcoin.com/api/v1/kline.do?symbol=%s&type=1min&size=5
      symbols: btc_usdt|BTCUSDT,eth_usdt|ETHUSDT